namespace Primify.Generators;

using System.Text;

public static class PrimifyRenderer
{
    public static string Render(PrimifyModel model)
    {
        var wrapper = RenderWrapper(model);
        var liteDb = RenderLiteDbInitializer(model);

        if (model.ContainingTypes.IsEmpty)
        {
            return $$"""
                     // <auto-generated/>
                     #nullable enable

                     using System;
                     using System.Runtime.CompilerServices;
                     using LiteDB;
                     using Primify.Converters;

                     namespace {{model.Namespace}};

                     {{liteDb}}

                     {{wrapper}}
                     """;
        }

        return $$"""
                 // <auto-generated/>
                 #nullable enable

                 using System;
                 using System.Runtime.CompilerServices;
                 using LiteDB;
                 using Primify.Converters;

                 namespace {{model.Namespace}}
                 {
                 {{Indent(liteDb)}}

                 {{RenderContainingTypes(model, wrapper)}}
                 }
                 """;
    }

    private static string RenderWrapper(PrimifyModel model)
    {
        var name = model.ClassName;
        var type = model.WrappedType;
        var modifier = model.IsValueType ? "readonly" : "sealed";

        var sb = new StringBuilder();
        sb.AppendLine($"[System.Text.Json.Serialization.JsonConverter(typeof(SystemTextJsonConverter<{name}, {type}>))]");
        sb.AppendLine($"[Newtonsoft.Json.JsonConverter(typeof(NewtonsoftJsonConverter<{name}, {type}>))]");
        sb.AppendLine($"{modifier} partial {model.Keyword} {name} : IPrimify<{name}, {type}>, IEquatable<{name}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public {type} Value {{ get; }}");
        sb.AppendLine();
        sb.AppendLine($"    private {name}({type} value) => Value = value;");
        sb.AppendLine();
        AppendFrom(sb, model);
        sb.AppendLine();
        AppendBsonCasting(sb, model);
        sb.AppendLine();
        AppendPrimitiveConversions(sb, model);
        if (!model.IsRecord)
        {
            var toStringBody = model.WrappedTypeIsReferenceType
                ? "Value?.ToString() ?? string.Empty"
                : "Value.ToString()";
            sb.AppendLine();
            sb.AppendLine($"    public override string ToString() => {toStringBody};");
        }

        var equalityMembers = GenerateEqualityMembers(model);
        if (!string.IsNullOrWhiteSpace(equalityMembers))
        {
            sb.AppendLine();
            sb.Append(Indent(equalityMembers));
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendFrom(StringBuilder sb, PrimifyModel model)
    {
        var name = model.ClassName;
        var type = model.WrappedType;

        sb.AppendLine($"    public static {name} From({type} value)");
        sb.AppendLine("    {");
        if (model.WrappedTypeIsReferenceType)
        {
            sb.AppendLine("        if (value is null)");
            sb.AppendLine("        {");
            sb.AppendLine("            throw new ArgumentNullException(nameof(value));");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("        var processedValue = value;");
        if (model.HasNormalize)
        {
            sb.AppendLine("        processedValue = Normalize(processedValue);");
        }

        if (model.HasValidate)
        {
            sb.AppendLine("        Validate(processedValue);");
        }

        sb.AppendLine($"        return new {name}(processedValue);");
        sb.AppendLine("    }");
    }

    private static void AppendPrimitiveConversions(StringBuilder sb, PrimifyModel model)
    {
        var name = model.ClassName;
        var type = model.WrappedType;

        // primitive -> wrapper runs normalization/validation and can throw; it must be explicit.
        sb.AppendLine($"    public static explicit operator {name}({type} value) => From(value);");
        sb.AppendLine($"    public static implicit operator {type}({name} value) => value.Value;");
    }

    private static void AppendBsonCasting(StringBuilder sb, PrimifyModel model)
    {
        var name = model.ClassName;
        var type = model.WrappedType;

        string toBson;
        switch (type)
        {
            case "System.DateOnly":
                toBson = "new LiteDB.BsonValue(value.Value.ToDateTime(System.TimeOnly.MinValue))";
                break;

            case "System.TimeOnly":
                toBson = "new LiteDB.BsonValue(value.Value.Ticks)";
                break;

            case "System.DateTimeOffset":
                toBson = "new LiteDB.BsonDocument\n                {\n                    [\"DateTime\"] = value.Value.UtcDateTime,\n                    [\"Offset\"] = value.Value.Offset.Ticks\n                }";
                break;

            default:
                toBson = "new LiteDB.BsonValue(value.Value)";
                break;
        }

        sb.AppendLine($"    public static implicit operator LiteDB.BsonValue({name} value) => {toBson};");

        if (type == "System.DateTimeOffset")
        {
            sb.AppendLine($"    public static implicit operator {name}(LiteDB.BsonValue value)");
            sb.AppendLine("    {");
            sb.AppendLine("        var doc = value.AsDocument;");
            sb.AppendLine("        var utcDateTime = doc[\"DateTime\"].AsDateTime;");
            sb.AppendLine("        var offset = new System.TimeSpan(doc[\"Offset\"].AsInt64);");
            sb.AppendLine("        var utcTime = new System.DateTimeOffset(utcDateTime);");
            sb.AppendLine("        var originalTime = utcTime.ToOffset(offset);");
            sb.AppendLine($"        return {name}.From(originalTime);");
            sb.AppendLine("    }");
        }
        else
        {
            sb.AppendLine($"    public static implicit operator {name}(LiteDB.BsonValue value) => {name}.From(({type})System.Convert.ChangeType(value.RawValue, typeof({type})));");
        }
    }

    private static string RenderContainingTypes(PrimifyModel model, string wrapper)
    {
        var text = Indent(wrapper, model.ContainingTypes.Items.Length);

        for (var index = model.ContainingTypes.Items.Length - 1; index >= 0; index--)
        {
            var containingType = model.ContainingTypes.Items[index];
            var indentation = new string(' ', index * 4);

            text = $$"""
                     {{indentation}}{{containingType.Declaration}}
                     {{indentation}}{
                     {{text}}
                     {{indentation}}}
                     """;
        }

        return text;
    }

    private static string Indent(string text, int levels = 1)
    {
        if (string.IsNullOrEmpty(text)) return text;
        var indentation = new string(' ', levels * 4);
        return indentation + text.Replace("\n", "\n" + indentation);
    }

    private static string GenerateEqualityMembers(PrimifyModel model)
    {
        var name = model.ClassName;
        var arg = model.WrappedType;
        var (equalsExpr, hashCodeExpr) = GetEqualityExpressions(arg);

        // For record types, let the compiler generate optimized equality
        if (model.IsRecord)
        {
            return string.Empty;
        }

        if (model.IsValueType)
        {
            return $$"""
                     public override bool Equals(object? obj) => obj is {{name}} other && Equals(other);

                     public bool Equals({{name}} other)
                     {
                         return {{equalsExpr("Value", "other.Value")}};
                     }

                     public override int GetHashCode() => {{hashCodeExpr("Value")}};

                     public static bool operator ==({{name}} left, {{name}} right) => left.Equals(right);
                     public static bool operator !=({{name}} left, {{name}} right) => !(left == right);
                     """;
        }

        return $$"""
                 public override bool Equals(object? obj) => obj is {{name}} other && Equals(other);

                 public bool Equals({{name}}? other)
                 {
                     if (ReferenceEquals(null, other)) return false;
                     if (ReferenceEquals(this, other)) return true;
                     return {{equalsExpr("Value", "other.Value")}};
                 }

                 public override int GetHashCode() => {{hashCodeExpr("Value")}};

                 public static bool operator ==({{name}}? left, {{name}}? right) => ReferenceEquals(left, right) || (left is not null && left.Equals(right));
                 public static bool operator !=({{name}}? left, {{name}}? right) => !(left == right);
                 """;
    }

    private static (Func<string, string, string> equalsExpr, Func<string, string> hashCodeExpr) GetEqualityExpressions(string wrappedType)
    {
        // For strings, use direct comparison for better performance
        if (wrappedType == "string" || wrappedType == "System.String")
        {
            return (
                (left, right) => $"string.Equals({left}, {right}, System.StringComparison.Ordinal)",
                value => $"{value}?.GetHashCode() ?? 0"
            );
        }

        // For primitive value types, use direct == operator
        if (IsPrimitiveValueType(wrappedType))
        {
            return (
                (left, right) => $"{left} == {right}",
                value => $"{value}.GetHashCode()"
            );
        }

        // For other types, fall back to EqualityComparer.Default
        return (
            (left, right) => $"System.Collections.Generic.EqualityComparer<{wrappedType}>.Default.Equals({left}, {right})",
            value => $"System.Collections.Generic.EqualityComparer<{wrappedType}>.Default.GetHashCode({value})"
        );
    }

    private static bool IsPrimitiveValueType(string type)
    {
        return type switch
        {
            "int" or "System.Int32" => true,
            "long" or "System.Int64" => true,
            "short" or "System.Int16" => true,
            "byte" or "System.Byte" => true,
            "bool" or "System.Boolean" => true,
            "char" or "System.Char" => true,
            "double" or "System.Double" => true,
            "float" or "System.Single" => true,
            "decimal" or "System.Decimal" => true,
            "Guid" or "System.Guid" => true,
            "DateTime" or "System.DateTime" => true,
            "DateTimeOffset" or "System.DateTimeOffset" => true,
            "DateOnly" or "System.DateOnly" => true,
            "TimeOnly" or "System.TimeOnly" => true,
            "TimeSpan" or "System.TimeSpan" => true,
            _ => false
        };
    }

    private static string RenderLiteDbInitializer(PrimifyModel model)
    {
        string name = model.FullyQualifiedTypeName;
        string initializerName = SanitizeIdentifier($"{model.TypeName}LiteDbInitializer");
        string arg = model.WrappedType;
        string serializeCode;
        string deserializeCode;

        switch (arg)
        {
            case "System.DateOnly":
                serializeCode = "wrapper => new LiteDB.BsonValue(wrapper.Value.ToDateTime(System.TimeOnly.MinValue))";
                deserializeCode = $"bson => {name}.From(System.DateOnly.FromDateTime(bson.AsDateTime))";
                break;

            case "System.TimeOnly":
                serializeCode = "wrapper => new LiteDB.BsonValue(wrapper.Value.Ticks)";
                deserializeCode = $"bson => {name}.From(new System.TimeOnly(bson.AsInt64))";
                break;

            case "System.DateTimeOffset":
                serializeCode = """
                                wrapper => new LiteDB.BsonDocument
                                    {
                                        ["DateTime"] = wrapper.Value.UtcDateTime,
                                        ["Offset"] = wrapper.Value.Offset.Ticks
                                    }
                                """;

                deserializeCode = $$"""
                                     bson =>
                                         {
                                             var doc = bson.AsDocument;
                                             var utcDateTime = doc["DateTime"].AsDateTime;
                                             var offset = new System.TimeSpan(doc["Offset"].AsInt64);
                                             var utcTime = new System.DateTimeOffset(utcDateTime);
                                             var originalTime = utcTime.ToOffset(offset);
                                             return {{name}}.From(originalTime);
                                         }
                                     """;
                break;

            default:
                serializeCode = "wrapper => new LiteDB.BsonValue(wrapper.Value)";
                deserializeCode =
                    $"bson => {name}.From(({arg})System.Convert.ChangeType(bson.RawValue, typeof({arg})))";
                break;
        }

        return $$"""
                 file static class {{initializerName}}
                 {
                     [System.Runtime.CompilerServices.ModuleInitializer]
                     internal static void Register()
                     {
                         LiteDB.BsonMapper.Global.RegisterType<{{name}}>(
                             serialize: {{serializeCode}},
                             deserialize: {{deserializeCode}}
                         );
                     }
                 }
                 """;
    }

    private static string SanitizeIdentifier(string value)
    {
        var characters = value.ToCharArray();
        for (var index = 0; index < characters.Length; index++)
        {
            if (!char.IsLetterOrDigit(characters[index]) && characters[index] != '_')
            {
                characters[index] = '_';
            }
        }

        return new string(characters);
    }
}
