namespace Primify.Generators;

using System.Text;

/// <summary>
/// Renders the generated source text for a <see cref="PrimifyModel"/>: the wrapper declaration,
/// its members, and the file-scoped LiteDB registration initializer.
/// </summary>
public static class PrimifyRenderer
{
    public static string Render(PrimifyModel model)
    {
        var wrapper = RenderWrapper(model);
        var liteDb = RenderLiteDbInitializer(model);

        if (model.ContainingTypes.IsEmpty)
        {
            return $$"""
                     // <auto-generated/>
                     #nullable enable

                     using System;
                     using System.Runtime.CompilerServices;
                     using Primify.Converters;

                     namespace {{model.Namespace}};

                     {{liteDb}}

                     {{wrapper}}
                     """;
        }

        return $$"""
                 // <auto-generated/>
                 #nullable enable

                 using System;
                 using System.Runtime.CompilerServices;
                 using Primify.Converters;

                 namespace {{model.Namespace}}
                 {
                 {{Indent(liteDb)}}

                 {{RenderContainingTypes(model, wrapper)}}
                 }
                 """;
    }

    private static string RenderWrapper(PrimifyModel model)
    {
        var name = model.ClassName;
        var type = model.WrappedType;
        var modifier = model.IsValueType ? "readonly" : "sealed";

        var sb = new StringBuilder();
        sb.AppendLine("[System.Diagnostics.DebuggerDisplay(\"{Value}\")]");
        sb.AppendLine($"[System.Text.Json.Serialization.JsonConverter(typeof(SystemTextJsonConverter<{name}, {type}>))]");
        sb.AppendLine($"[Newtonsoft.Json.JsonConverter(typeof(NewtonsoftJsonConverter<{name}, {type}>))]");
        sb.AppendLine($"{modifier} partial {model.Keyword} {name} : IPrimify<{name}, {type}>, IEquatable<{name}>");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Gets the wrapped primitive value.</summary>");
        sb.AppendLine($"    public {type} Value {{ get; }}");
        sb.AppendLine();
        sb.AppendLine($"    private {name}({type} value) => Value = value;");
        sb.AppendLine();
        AppendFrom(sb, model);
        sb.AppendLine();
        AppendTryFrom(sb, model);
        sb.AppendLine();
        AppendPrimitiveConversions(sb, model);
        if (!model.IsRecord)
        {
            var toStringBody = model.WrappedTypeIsReferenceType
                ? "Value?.ToString() ?? string.Empty"
                : "Value.ToString()";
            sb.AppendLine();
            sb.AppendLine("    /// <summary>Returns the string form of the underlying value.</summary>");
            sb.AppendLine($"    public override string ToString() => {toStringBody};");
        }

        var equalityMembers = GenerateEqualityMembers(model);
        if (!string.IsNullOrWhiteSpace(equalityMembers))
        {
            sb.AppendLine();
            sb.Append(Indent(equalityMembers));
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendFrom(StringBuilder sb, PrimifyModel model)
    {
        var name = model.ClassName;
        var type = model.WrappedType;

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Creates a validated instance by running the declaring type's Normalize hook");
        sb.AppendLine("    /// followed by its Validate hook.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"value\">The primitive value to wrap.</param>");
        sb.AppendLine("    /// <returns>The validated wrapper instance.</returns>");
        sb.AppendLine("    /// <exception cref=\"ArgumentException\">Thrown when validation rejects the value; also covers ArgumentNullException for null reference-type values.</exception>");
        sb.AppendLine($"    public static {name} From({type} value)");
        sb.AppendLine("    {");
        if (model.WrappedTypeIsReferenceType)
        {
            sb.AppendLine("        if (value is null)");
            sb.AppendLine("        {");
            sb.AppendLine("            throw new ArgumentNullException(nameof(value));");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("        var processedValue = value;");
        if (model.HasNormalize)
        {
            sb.AppendLine("        processedValue = Normalize(processedValue);");
        }

        if (model.HasValidate)
        {
            sb.AppendLine("        Validate(processedValue);");
        }

        sb.AppendLine($"        return new {name}(processedValue);");
        sb.AppendLine("    }");
    }

    private static void AppendTryFrom(StringBuilder sb, PrimifyModel model)
    {
        var name = model.ClassName;
        var type = model.WrappedType;

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Non-throwing alternative to <see cref=\"From\"/>. Applies the same Normalize and");
        sb.AppendLine("    /// Validate hooks; returns false when validation throws an ArgumentException-derived");
        sb.AppendLine("    /// exception.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"value\">The primitive value to wrap.</param>");
        sb.AppendLine("    /// <param name=\"result\">The validated instance, or default when creation fails.</param>");
        sb.AppendLine("    /// <returns>true when the value passed validation; otherwise false.</returns>");
        sb.AppendLine($"    public static bool TryFrom({type} value, out {name} result)");
        sb.AppendLine("    {");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            result = From(value);");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (ArgumentException)");
        sb.AppendLine("        {");
        sb.AppendLine("            result = default!;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static void AppendPrimitiveConversions(StringBuilder sb, PrimifyModel model)
    {
        var name = model.ClassName;
        var type = model.WrappedType;

        // primitive -> wrapper runs normalization/validation and can throw; it must be explicit.
        sb.AppendLine("    /// <summary>Wraps the primitive through the same normalize/validate pipeline as <see cref=\"From\"/>.</summary>");
        sb.AppendLine("    /// <param name=\"value\">The primitive value to wrap.</param>");
        sb.AppendLine($"    public static explicit operator {name}({type} value) => From(value);");
        sb.AppendLine("    /// <summary>Returns the underlying primitive value.</summary>");
        sb.AppendLine("    /// <param name=\"value\">The wrapper instance.</param>");
        sb.AppendLine($"    public static implicit operator {type}({name} value) => value.Value;");
    }

    private static string RenderContainingTypes(PrimifyModel model, string wrapper)
    {
        var text = Indent(wrapper, model.ContainingTypes.Items.Length);

        for (var index = model.ContainingTypes.Items.Length - 1; index >= 0; index--)
        {
            var containingType = model.ContainingTypes.Items[index];
            var indentation = new string(' ', index * 4);

            text = $$"""
                     {{indentation}}{{containingType.Declaration}}
                     {{indentation}}{
                     {{text}}
                     {{indentation}}}
                     """;
        }

        return text;
    }

    private static string Indent(string text, int levels = 1)
    {
        if (string.IsNullOrEmpty(text)) return text;
        var indentation = new string(' ', levels * 4);
        return indentation + text.Replace("\n", "\n" + indentation);
    }

    private static string GenerateEqualityMembers(PrimifyModel model)
    {
        var name = model.ClassName;
        var arg = model.WrappedType;
        var (equalsExpr, hashCodeExpr) = GetEqualityExpressions(arg);

        // For record types, let the compiler generate optimized equality
        if (model.IsRecord)
        {
            return string.Empty;
        }

        if (model.IsValueType)
        {
            return $$"""
                     /// <summary>Determines whether the specified object wraps an equal value.</summary>
                     public override bool Equals(object? obj) => obj is {{name}} other && Equals(other);

                     /// <summary>Determines whether the other instance wraps an equal value.</summary>
                     public bool Equals({{name}} other)
                     {
                         return {{equalsExpr("Value", "other.Value")}};
                     }

                     /// <summary>Returns a hash code based on the underlying value.</summary>
                     public override int GetHashCode() => {{hashCodeExpr("Value")}};

                     /// <summary>Compares two instances by their underlying values.</summary>
                     public static bool operator ==({{name}} left, {{name}} right) => left.Equals(right);

                     /// <summary>Compares two instances by their underlying values.</summary>
                     public static bool operator !=({{name}} left, {{name}} right) => !(left == right);
                     """;
        }

        return $$"""
                 /// <summary>Determines whether the specified object wraps an equal value.</summary>
                 public override bool Equals(object? obj) => obj is {{name}} other && Equals(other);

                 /// <summary>Determines whether the other instance wraps an equal value.</summary>
                 public bool Equals({{name}}? other)
                 {
                     if (ReferenceEquals(null, other)) return false;
                     if (ReferenceEquals(this, other)) return true;
                     return {{equalsExpr("Value", "other.Value")}};
                 }

                 /// <summary>Returns a hash code based on the underlying value.</summary>
                 public override int GetHashCode() => {{hashCodeExpr("Value")}};

                 /// <summary>Compares two instances by their underlying values; null references are equal only to each other.</summary>
                 public static bool operator ==({{name}}? left, {{name}}? right) => ReferenceEquals(left, right) || (left is not null && left.Equals(right));

                 /// <summary>Compares two instances by their underlying values.</summary>
                 public static bool operator !=({{name}}? left, {{name}}? right) => !(left == right);
                 """;
    }

    private static (Func<string, string, string> equalsExpr, Func<string, string> hashCodeExpr) GetEqualityExpressions(string wrappedType)
    {
        // For strings, use direct comparison for better performance
        if (wrappedType == "string" || wrappedType == "System.String")
        {
            return (
                (left, right) => $"string.Equals({left}, {right}, System.StringComparison.Ordinal)",
                value => $"{value}?.GetHashCode() ?? 0"
            );
        }

        // For primitive value types, use direct == operator
        if (IsPrimitiveValueType(wrappedType))
        {
            return (
                (left, right) => $"{left} == {right}",
                value => $"{value}.GetHashCode()"
            );
        }

        // For other types, fall back to EqualityComparer.Default
        return (
            (left, right) => $"System.Collections.Generic.EqualityComparer<{wrappedType}>.Default.Equals({left}, {right})",
            value => $"System.Collections.Generic.EqualityComparer<{wrappedType}>.Default.GetHashCode({value})"
        );
    }

    private static bool IsPrimitiveValueType(string type)
    {
        return type switch
        {
            "int" or "System.Int32" => true,
            "long" or "System.Int64" => true,
            "short" or "System.Int16" => true,
            "byte" or "System.Byte" => true,
            "bool" or "System.Boolean" => true,
            "char" or "System.Char" => true,
            "double" or "System.Double" => true,
            "float" or "System.Single" => true,
            "decimal" or "System.Decimal" => true,
            "Guid" or "System.Guid" => true,
            "DateTime" or "System.DateTime" => true,
            "DateTimeOffset" or "System.DateTimeOffset" => true,
            "DateOnly" or "System.DateOnly" => true,
            "TimeOnly" or "System.TimeOnly" => true,
            "TimeSpan" or "System.TimeSpan" => true,
            _ => false
        };
    }

    private static string RenderLiteDbInitializer(PrimifyModel model)
    {
        string name = model.FullyQualifiedTypeName;
        string initializerName = SanitizeIdentifier($"{model.TypeName}LiteDbInitializer");
        string arg = model.WrappedType;

        return $$"""
                 file static class {{initializerName}}
                 {
                     [System.Runtime.CompilerServices.ModuleInitializer]
                     internal static void Register()
                     {
                         Primify.Converters.LiteDbMapping.Register<{{name}}, {{arg}}>();
                     }
                 }
                 """;
    }

    private static string SanitizeIdentifier(string value)
    {
        var characters = value.ToCharArray();
        for (var index = 0; index < characters.Length; index++)
        {
            if (!char.IsLetterOrDigit(characters[index]) && characters[index] != '_')
            {
                characters[index] = '_';
            }
        }

        return new string(characters);
    }
}
